# Generated by Django 4.2.30 on 2026-07-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc_aadhaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_apaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_caste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_tc_lc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_tenth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_twelfth',
            field=models.BooleanField(default=False),
        ),
    ]
