# Generated by Django 4.2.30 on 2026-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_doc_aadhaar_student_doc_apaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
