# Generated by Django 4.2.30 on 2026-07-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_is_claimed_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_claimed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
    ]
