# Generated by Django 4.2.30 on 2026-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_student_is_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
