# Generated by Django 4.2.30 on 2026-07-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_student_active_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, choices=[('AIML', 'AIML'), ('AIRO', 'AIRO')], max_length=10, null=True),
        ),
    ]
