server {
    listen 80;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias "/home/shruten-vala/Desktop/copied/Parul_Admissions_System (Copy)/Admission-app-main/staticfiles/";
    }

    location / {
        include proxy_params;
        proxy_pass "http://unix:/home/shruten-vala/Desktop/copied/Parul_Admissions_System (Copy)/Admission-app-main/gunicorn.sock";
    }
}
